### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jaylac2000** [YellowBanana508/BClanUI#1]
running **/clanui** in console crashes the server. please add a message to say "Use this command in game" or something

**Comment by YellowBanana508** [comment]
Oh hi thanks for reaching out,  I know that this happens, I will fix it when the next update comes out, the code is really rubbish and I will fix it soon :D. Thanks for trying the plugin 😉😉
If you need further help you can contact me on discord 
YellowBanana#0001

**Comment by jaylac2000** [comment]
Np. I use BedrockClans for my Prisons Server. So thought I would check this out when I saw it. I have not actually tested the plugin yet

**Comment by YellowBanana508** [comment]
Test it, it's awesome, haven't coded it correctly, but it works :D

**Comment by YellowBanana508** [comment]
This issue is now fixed in latest update so I am closing this Issue :)
